on:
  schedule:
  - cron: '00 20 * * *'
push:
  branches: main

name: Scrape Ukrainian refugees data

jobs:
  render:
  name: Scrape Ukrainian refugees data
runs-on: macOS-latest
steps:
  - uses: actions/checkout@v2
  - uses: r-lib/actions/setup-r@v1
  - name: Install dependencies
    run: Rscript -e 'install.packages(c("tidyverse","lubridate", "rjson"))'
  - name: Scrape the data
    run: Rscript ukrainian_refugees_report.R
  - name: Commit results
    run: |
      git add -A
      git commit -m 'New refugees data added - updating processed!' || echo "No changes to commit"
      git push origin || echo "No changes to commit"